version: '3.8'

services:
  db:
    image: postgres:15
    container_name: user-service_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: users
    ports:
      - "5111:5432" #5111 - Внешний порт
    volumes:
      - postgres_data:/vars/lib/postgresql/data
    restart: always

volumes:
  postgres_data: